CREATE TABLE USERS (
    ID INTEGER,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    PRIMARY KEY(ID)
)
;

CREATE TABLE SCHOOLS_AND_UNIVERSITIES (
    ID INTEGER,
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    LOCATION TEXT NOT NULL,
    YEAR NUMERIC NOT NULL,
    PRIMARY KEY(ID)
)
;

CREATE TABLE COMPANIES (
    ID INTEGER,
    NAME TEXT NOT NULL,
    INDUSTRY TEXT NOT NULL,
    LOCATION TEXT NOT NULL,
    PRIMARY KEY(ID)
)
;

CREATE TABLE CONNECTIONS (
    ID INTEGER,
    SCHOOL_AND_UNIVERSITY_START_DATE NUMERIC NOT NULL,
    SCHOOL_AND_UNIVERSITY_END_DATE NUMERIC,
    SCHOOL_AND_UNIVERSITY_DEGREE TEXT NOT NULL,
    COMPANY_START_DATE NUMERIC NOT NULL,
    COMPANY_END_DATE NUMERIC,
    COMPANY_TITLE TEXT NOT NULL,
    USER_ID INTEGER,
    TO_USER_ID INTEGER,
    TO_SCHOOL_AND_UNIVERSITY_ID INTEGER,
    TO_COMPANY_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(TO_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(TO_SCHOOL_AND_UNIVERSITY_ID) REFERENCES SCHOOLS_AND_UNIVERSITIES(ID),
    FOREIGN KEY(TO_COMPANY_ID) REFERENCES COMPANIES(ID)
)
;
