CREATE VIEW FREQUENTLY_REVIEWED AS
SELECT
    L.ID,
    PROPERTY_TYPE,
    HOST_NAME,
    COUNT(R.ID) AS REVIEWS
FROM REVIEWS R
JOIN LISTINGS L
    ON R.LISTING_ID = L.ID
GROUP BY
    L.ID,
    PROPERTY_TYPE,
    HOST_NAME
ORDER BY REVIEWS DESC
LIMIT 100
;
