CREATE VIEW JUNE_VACANCIES AS
SELECT
    L.ID,
    PROPERTY_TYPE,
    HOST_NAME,
    COUNT(*) AS 'days_vacant'
FROM AVAILABILITIES A
JOIN LISTINGS L
    ON A.LISTING_ID = L.ID
WHERE 
    AVAILABLE = 'TRUE'
    AND DATE BETWEEN '2023-06-01' AND '2023-06-30'
GROUP BY
    L.ID,
    PROPERTY_TYPE,
    HOST_NAME
;
