CREATE TABLE BOOK_CIPHER (
    ID INTEGER,
    SENTENCE_NUMBER INTEGER NOT NULL,
    CHARACTER_NUMBER INTEGER NOT NULL,
    MESSAGE_LENGTH INTEGER NOT NULL,
    PRIMARY KEY(ID)
)
;

INSERT INTO BOOK_CIPHER (SENTENCE_NUMBER, CHARACTER_NUMBER, MESSAGE_LENGTH)
VALUES
    (14, 98, 4),
    (114, 3, 5),
    (618, 72, 9),
    (630, 7, 3),
    (932, 12, 5),
    (2230, 50, 7),
    (2346, 44, 10),
    (3041, 14, 5)
;

CREATE VIEW MESSAGE AS
SELECT SUBSTR(S.SENTENCE, BC.CHARACTER_NUMBER, BC.MESSAGE_LENGTH) AS 'phrase'
FROM BOOK_CIPHER BC
JOIN SENTENCES S
    ON BC.SENTENCE_NUMBER = S.ID
;
