CREATE TABLE METEORITES (
    ID INTEGER,
    NAME TEXT NOT NULL,
    CLASS TEXT NOT NULL,
    MASS REAL,
    DISCOVERY TEXT NOT NULL CHECK(DISCOVERY IN ('Fell', 'Found')),
    YEAR NUMERIC,
    LAT REAL,
    LONG REAL,
    PRIMARY KEY(ID)
)
;

CREATE TABLE METEORITES_TEMP (
    NAME TEXT,
    ID INTEGER,
    NAMETYPE TEXT,
    CLASS TEXT,
    MASS REAL,
    DISCOVERY TEXT,
    YEAR NUMERIC,
    LAT REAL,
    LONG REAL
)
;

.import --csv --skip 1 meteorites.csv METEORITES_TEMP

UPDATE METEORITES_TEMP
SET MASS = NULL
WHERE MASS = ''
;

UPDATE METEORITES_TEMP
SET YEAR = NULL
WHERE YEAR = ''
;

UPDATE METEORITES_TEMP
SET LAT = NULL
WHERE LAT = ''
;

UPDATE METEORITES_TEMP
SET LONG = NULL
WHERE LONG = ''
;

INSERT INTO METEORITES (
    NAME, 
    CLASS, 
    MASS, 
    DISCOVERY, 
    YEAR, 
    LAT, 
    LONG
)
SELECT 
    NAME, 
    CLASS, 
    ROUND(MASS, 2), 
    DISCOVERY, 
    YEAR, 
    ROUND(LAT, 2), 
    ROUND(LONG, 2)
FROM METEORITES_TEMP
WHERE NAMETYPE <> 'Relict'
ORDER BY 
    YEAR, 
    NAME
;

DROP TABLE METEORITES_TEMP;
