CREATE INDEX SEARCH_MESSAGES_BY_FROM_USER_ID 
    ON MESSAGES(FROM_USER_ID)
;

WITH TOP_USERS AS (
    SELECT
        TO_USER_ID AS USER_ID,
        COUNT(*) AS NUMBER_OF_MESSAGES
    FROM MESSAGES
    WHERE FROM_USER_ID = (
        SELECT ID
        FROM USERS
        WHERE USERNAME = 'creativewisdom377'
    )
    GROUP BY TO_USER_ID
    ORDER BY NUMBER_OF_MESSAGES DESC
    LIMIT 3
)

SELECT USER_ID
FROM TOP_USERS
;
