CREATE INDEX SEARCH_MESSAGES_BY_TO_USER_ID
    ON MESSAGES(TO_USER_ID)
;

WITH MOST_POPULAR AS (
    SELECT
        TO_USER_ID AS USER_ID,
        COUNT(*) AS NUMBER_OF_MESSAGES
    FROM MESSAGES
    GROUP BY TO_USER_ID
    ORDER BY NUMBER_OF_MESSAGES DESC
    LIMIT 1
)

SELECT USERNAME
FROM USERS
WHERE ID = (
    SELECT USER_ID
    FROM MOST_POPULAR
)
;
