CREATE TABLE PASSENGERS (
    ID INTEGER,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    AGE INTEGER NOT NULL,
    PRIMARY KEY(ID)
)
;

CREATE TABLE AIRLINES (
    ID INTEGER,
    NAME TEXT NOT NULL,
    CONCOURSE TEXT NOT NULL CHECK(CONCOURSE IN ('A', 'B', 'C', 'D', 'E', 'F', 'T')),
    PRIMARY KEY(ID)
)
;

CREATE TABLE FLIGHTS (
    ID INTEGER,
    FLIGHT_NUMBER INTEGER NOT NULL,
    FROM_AIRPORT_CODE TEXT NOT NULL,
    TO_AIRPORT_CODE TEXT NOT NULL,
    DEPARTURE_DATETIME NUMERIC NOT NULL,
    ARRIVAL_DATETIME NUMERIC NOT NULL,
    AIRLINE_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY(AIRLINE_ID) REFERENCES AIRLINES(ID)
)
;


CREATE TABLE CHECK_INS (
    ID INTEGER,
    DATETIME NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PASSENGER_ID INTEGER,
    FLIGHT_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGERS(ID),
    FOREIGN KEY(FLIGHT_ID) REFERENCES FLIGHTS(ID)
)
;
