CREATE INDEX DEPARTMENT_INDEX
    ON COURSES(DEPARTMENT)
;

CREATE INDEX COURSE_NUMBER_INDEX
    ON COURSES(NUMBER)
;

CREATE INDEX SEMESTER_INDEX
    ON COURSES(SEMESTER)
;

CREATE INDEX COURSE_TITLE_INDEX
    ON COURSES(TITLE)
;
