CREATE TABLE INGREDIENTS (
    ID INTEGER,
    INGREDIENT TEXT NOT NULL,
    PRICE REAL NOT NULL,
    UNIT TEXT NOT NULL,
    PRIMARY KEY(ID)
)
;

CREATE TABLE DONUTS (
    ID INTEGER,
    NAME TEXT NOT NULL,
    IS_GLUTEN_FREE INTEGER NOT NULL CHECK(IS_GLUTEN_FREE IN (0, 1)) DEFAULT 0,
    PRICE REAL NOT NULL,
    INGREDIENT_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY(INGREDIENT_ID) REFERENCES INGREDIENTS(ID)
)
;

CREATE TABLE ORDERS (
    ID INTEGER,
    ORDER_CODE INTEGER NOT NULL,
    DONUT_ID INTEGER,
    CUSTOMER_ID INTEGER UNIQUE,
    PRIMARY KEY(ID),
    FOREIGN KEY(DONUT_ID) REFERENCES DONUTS(ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
)
;

CREATE TABLE CUSTOMERS (
    ID INTEGER,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    ORDER_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID)
)
;
